version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "127.0.0.1:8086:8000"
    env_file:
      - .env.prod
    volumes:
      - ./data:/usr/app/data
    restart: always
