version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/app
    ports:
      - 127.0.0.1:8080:8000
    environment:
      - PYTHONUNBUFFERED=1


  tailwind:
    build:
      dockerfile: Dockerfile
      target: dev
    tty: true
    volumes:
      - .:/usr/app
    command: tailwindcss -i ./tailwind/input.css -o ./schedulr/static/main.css --watch
